repos:
  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: "v0.9.9"
  #   hooks:
  #     - id: ruff
  #       args: ["--exclude", "*.ipynb"]
  #     - id: ruff-format
  #       args: ["--exclude", "*.ipynb"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
