_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
batch_size:
    value: 16
bit_depth:
    value: 24
c0:
    value: 0
c1:
    value: 0
cond_dim:
    value: 2
criterion1:
    value: stft
criterion2:
    value: smooth
current_epoch:
    value: 126
dataset:
    value: egfxset
dilation_growth:
    value: 256
early_stop_patience:
    value: 50
in_ch:
    value: 1
kernel_size:
    value: 3
lr:
    value: 0.01
lr_patience:
    value: 10
lr_scheduler:
    value: ReduceLROnPlateau
max_epochs:
    value: 500
min_valid_loss:
    value: 1.1794837713241577
model_type:
    value: GCN
n_blocks:
    value: 3
n_channels:
    value: 64
name:
    value: GCN-3
num_workers:
    value: 16
optimizer:
    value: Adam
out_ch:
    value: 1
params:
    value: 61312
pre_emphasis:
    value: null
sample_rate:
    value: 48000
timestamp:
    value: 20240324-164936
